/*
 * Copyright 2018 Filippo.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package it.filippo.stella.dmxdashboard.View.Panels;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

/**
 *
 * @author Filippo
 */
public class PanelLuci extends javax.swing.JPanel implements MouseListener {
    
    private Color c;

    /**
     * Creates new form MainPanel
     */
    public PanelLuci() {
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelLuci = new javax.swing.JPanel();
        jButtonRimuovi = new javax.swing.JButton();
        jButtonModifica = new javax.swing.JButton();
        jButtonAggiungi = new javax.swing.JButton();

        setBackground(new java.awt.Color(37, 50, 55));
        setForeground(new java.awt.Color(248, 248, 255));
        setMinimumSize(new java.awt.Dimension(800, 570));
        setPreferredSize(new java.awt.Dimension(800, 570));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 248, 255)));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(350, 534));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(350, 534));

        jPanelLuci.setBackground(new java.awt.Color(37, 50, 55));
        jPanelLuci.setForeground(new java.awt.Color(248, 248, 255));
        jPanelLuci.setLayout(new javax.swing.BoxLayout(jPanelLuci, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanelLuci);

        jButtonRimuovi.setBackground(new java.awt.Color(37, 50, 55));
        jButtonRimuovi.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButtonRimuovi.setForeground(new java.awt.Color(248, 248, 255));
        jButtonRimuovi.setText("Rimuovi Lampada");
        jButtonRimuovi.setBorder(null);
        jButtonRimuovi.setBorderPainted(false);
        jButtonRimuovi.setFocusPainted(false);
        jButtonRimuovi.setMaximumSize(new java.awt.Dimension(170, 40));
        jButtonRimuovi.setMinimumSize(new java.awt.Dimension(170, 40));
        jButtonRimuovi.setPreferredSize(new java.awt.Dimension(170, 40));

        jButtonModifica.setBackground(new java.awt.Color(37, 50, 55));
        jButtonModifica.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButtonModifica.setForeground(new java.awt.Color(248, 248, 255));
        jButtonModifica.setText("Modifica Lampada");
        jButtonModifica.setBorder(null);
        jButtonModifica.setBorderPainted(false);
        jButtonModifica.setFocusPainted(false);
        jButtonModifica.setMaximumSize(new java.awt.Dimension(170, 40));
        jButtonModifica.setMinimumSize(new java.awt.Dimension(170, 40));
        jButtonModifica.setPreferredSize(new java.awt.Dimension(170, 40));

        jButtonAggiungi.setBackground(new java.awt.Color(37, 50, 55));
        jButtonAggiungi.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButtonAggiungi.setForeground(new java.awt.Color(248, 248, 255));
        jButtonAggiungi.setText("Aggiungi Lampada");
        jButtonAggiungi.setBorder(null);
        jButtonAggiungi.setBorderPainted(false);
        jButtonAggiungi.setFocusPainted(false);
        jButtonAggiungi.setMaximumSize(new java.awt.Dimension(170, 40));
        jButtonAggiungi.setMinimumSize(new java.awt.Dimension(170, 40));
        jButtonAggiungi.setPreferredSize(new java.awt.Dimension(170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRimuovi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jButtonRimuovi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Variables declaration"> 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAggiungi;
    private javax.swing.JButton jButtonModifica;
    private javax.swing.JButton jButtonRimuovi;
    private javax.swing.JPanel jPanelLuci;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    // </editor-fold> 
    
    // <editor-fold defaultstate="collapsed" desc="Mouse Listener"> 
    //Implementation of mouse listener for JColorChooser
    @Override
    public void mouseClicked(MouseEvent e) {
    }
    @Override
    public void mousePressed(MouseEvent e) {}
    @Override
    public void mouseReleased(MouseEvent e) {}
    @Override
    public void mouseEntered(MouseEvent e) {}
    @Override
    public void mouseExited(MouseEvent e) {}
    // </editor-fold> 
}
