/*
 * Copyright 2018 Filippo.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package it.filippo.stella.dmxdashboard.View.Panels;

import it.filippo.stella.dmxdashboard.Model.ApplicationCore;
import it.filippo.stella.dmxdashboard.Model.Luce;
import it.filippo.stella.dmxdashboard.View.Dialogs.LightDialog;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;

/**
 *
 * @author Filippo
 */
public class PanelLuci extends javax.swing.JPanel implements ActionListener {

    private final ApplicationCore ac;
    private final LightDialog ld;
    private Color c;

    public PanelLuci(ApplicationCore ac, LightDialog ld) {
        this.ac = ac;
        this.ld = ld;
        this.ld.setPl(this);
        this.initComponents();
        this.refreshLuci();
        this.jButtonAggiungi.addActionListener(this);
        this.jButtonModifica.addActionListener(this);
        this.jButtonRimuovi.addActionListener(this);
    }

    public final void refreshLuci() {
        this.ac.sortArray();
        DefaultListModel<String> model = new DefaultListModel<>();
        for(int i=0;i<this.ac.getLightNumber();i++){
            Luce l = this.ac.getLuce(i);
            model.addElement(l.getTipo() + " | Start: " + l.getStart());
        }
        this.jListLuci.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListLuci = new javax.swing.JList<>();
        jButtonRimuovi = new javax.swing.JButton();
        jButtonModifica = new javax.swing.JButton();
        jButtonAggiungi = new javax.swing.JButton();

        setBackground(new java.awt.Color(37, 50, 55));
        setForeground(new java.awt.Color(248, 248, 255));
        setMinimumSize(new java.awt.Dimension(800, 570));
        setPreferredSize(new java.awt.Dimension(800, 570));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 248, 255)));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(350, 534));
        jScrollPane1.setName(""); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(350, 534));

        jListLuci.setBackground(new java.awt.Color(37, 50, 55));
        jListLuci.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jListLuci.setForeground(new java.awt.Color(248, 248, 255));
        jListLuci.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListLuci.setLayoutOrientation(javax.swing.JList.VERTICAL_WRAP);
        jScrollPane1.setViewportView(jListLuci);

        jButtonRimuovi.setBackground(new java.awt.Color(37, 50, 55));
        jButtonRimuovi.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButtonRimuovi.setForeground(new java.awt.Color(248, 248, 255));
        jButtonRimuovi.setText("Rimuovi Lampada");
        jButtonRimuovi.setBorder(null);
        jButtonRimuovi.setBorderPainted(false);
        jButtonRimuovi.setFocusPainted(false);
        jButtonRimuovi.setMaximumSize(new java.awt.Dimension(170, 40));
        jButtonRimuovi.setMinimumSize(new java.awt.Dimension(170, 40));
        jButtonRimuovi.setPreferredSize(new java.awt.Dimension(170, 40));

        jButtonModifica.setBackground(new java.awt.Color(37, 50, 55));
        jButtonModifica.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButtonModifica.setForeground(new java.awt.Color(248, 248, 255));
        jButtonModifica.setText("Modifica Lampada");
        jButtonModifica.setBorder(null);
        jButtonModifica.setBorderPainted(false);
        jButtonModifica.setFocusPainted(false);
        jButtonModifica.setMaximumSize(new java.awt.Dimension(170, 40));
        jButtonModifica.setMinimumSize(new java.awt.Dimension(170, 40));
        jButtonModifica.setPreferredSize(new java.awt.Dimension(170, 40));

        jButtonAggiungi.setBackground(new java.awt.Color(37, 50, 55));
        jButtonAggiungi.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButtonAggiungi.setForeground(new java.awt.Color(248, 248, 255));
        jButtonAggiungi.setText("Aggiungi Lampada");
        jButtonAggiungi.setBorder(null);
        jButtonAggiungi.setBorderPainted(false);
        jButtonAggiungi.setFocusPainted(false);
        jButtonAggiungi.setMaximumSize(new java.awt.Dimension(170, 40));
        jButtonAggiungi.setMinimumSize(new java.awt.Dimension(170, 40));
        jButtonAggiungi.setPreferredSize(new java.awt.Dimension(170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRimuovi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModifica, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jButtonRimuovi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Variables declaration"> 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAggiungi;
    private javax.swing.JButton jButtonModifica;
    private javax.swing.JButton jButtonRimuovi;
    private javax.swing.JList<String> jListLuci;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    // </editor-fold> 

    public JButton getjButtonAggiungi() {
        return this.jButtonAggiungi;
    }

    public JButton getjButtonModifica() {
        return this.jButtonModifica;
    }

    public JButton getjButtonRimuovi() {
        return this.jButtonRimuovi;
    }

    public JList getjListLuci() {
        return this.jListLuci;
    }

    // <editor-fold defaultstate="collapsed" desc="Action Listener"> 
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == this.jButtonAggiungi) {
            this.ld.setLocationRelativeTo(this.getParent());
            this.ld.resetDialog();
            this.ld.setVisible(true);
        } else if (e.getSource() == this.jButtonModifica && this.jListLuci.getSelectedIndex()!=-1) {
            this.ld.setLocationRelativeTo(this.getParent());
            this.ld.loadLamp(this.ac.getLuce(this.jListLuci.getSelectedIndex()), this.jListLuci.getSelectedIndex());
            this.ld.setVisible(true);
        } else if (e.getSource() == this.jButtonRimuovi && this.jListLuci.getSelectedIndex()!=-1) {
            this.ac.removeLuce(this.jListLuci.getSelectedIndex());
            this.refreshLuci();
        }
    }
    // </editor-fold> 

}
