/*
 * Copyright 2018 Stella Filippo.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package it.filippo.stella.dmxdashboard.View.Dialogs;

import it.filippo.stella.dmxdashboard.Model.ApplicationCore;
import it.filippo.stella.dmxdashboard.Model.Luce;
import it.filippo.stella.dmxdashboard.View.Panels.PanelLuci;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Stella Filippo
 * @version 1.0
 */
public class LightDialog extends javax.swing.JDialog implements ActionListener, ChangeListener{

    private final ApplicationCore ac;
    private PanelLuci pl;
    private boolean isEdit=false;
    private Integer index;
    
    public LightDialog(java.awt.Frame parent, ApplicationCore ac, boolean modal) {
        super(parent, modal);
        this.ac = ac;
        this.initComponents();
        this.setLocationRelativeTo(parent);
        this.pack();
        this.jComboBoxTipo.addActionListener(this);
        this.jButtonConferma.addActionListener(this);
        this.jButtonAnnulla.addActionListener(this);
        this.jSpinnerR.addChangeListener(this);
    }

    public void resetDialog(){
        this.jComboBoxTipo.setSelectedIndex(0);
        this.jSpinnerR.setValue(0);
        this.jSpinnerG.setValue(0);
        this.jSpinnerB.setValue(0);
        this.jSpinnerG.setEnabled(true);
        this.jSpinnerB.setEnabled(true);
    }
    
    public void loadLamp(Luce l, Integer index){
        this.jComboBoxTipo.setSelectedItem(l.getTipo());
        this.jSpinnerR.setValue(l.getCanaleR());
        this.jSpinnerG.setValue(l.getCanaleG());
        this.jSpinnerB.setValue(l.getCanaleB());
        this.isEdit=true;
        this.index = index;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerR = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerG = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerB = new javax.swing.JSpinner();
        jButtonConferma = new javax.swing.JButton();
        jButtonAnnulla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lampada");

        jPanel1.setBackground(new java.awt.Color(37, 50, 55));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 248, 255));
        jLabel1.setText("Tipo Lampada");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Generic DMX", "RGB Lamp" }));
        jComboBoxTipo.setMaximumSize(new java.awt.Dimension(180, 30));
        jComboBoxTipo.setMinimumSize(new java.awt.Dimension(180, 30));
        jComboBoxTipo.setPreferredSize(new java.awt.Dimension(180, 30));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 248, 255));
        jLabel2.setText("Canale G");

        jSpinnerR.setModel(new javax.swing.SpinnerNumberModel(0, 0, 512, 1));
        jSpinnerR.setBorder(null);
        jSpinnerR.setMaximumSize(new java.awt.Dimension(120, 22));
        jSpinnerR.setMinimumSize(new java.awt.Dimension(120, 22));
        jSpinnerR.setPreferredSize(new java.awt.Dimension(120, 22));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(248, 248, 255));
        jLabel3.setText("Canale R");

        jSpinnerG.setModel(new javax.swing.SpinnerNumberModel(0, 0, 512, 1));
        jSpinnerG.setBorder(null);
        jSpinnerG.setMaximumSize(new java.awt.Dimension(120, 22));
        jSpinnerG.setMinimumSize(new java.awt.Dimension(120, 22));
        jSpinnerG.setPreferredSize(new java.awt.Dimension(120, 22));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(248, 248, 255));
        jLabel4.setText("Canale B");

        jSpinnerB.setModel(new javax.swing.SpinnerNumberModel(0, 0, 512, 1));
        jSpinnerB.setBorder(null);
        jSpinnerB.setMaximumSize(new java.awt.Dimension(120, 22));
        jSpinnerB.setMinimumSize(new java.awt.Dimension(120, 22));
        jSpinnerB.setPreferredSize(new java.awt.Dimension(120, 22));

        jButtonConferma.setBackground(new java.awt.Color(37, 50, 55));
        jButtonConferma.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButtonConferma.setForeground(new java.awt.Color(248, 248, 255));
        jButtonConferma.setText("Conferma");
        jButtonConferma.setBorder(null);
        jButtonConferma.setFocusPainted(false);

        jButtonAnnulla.setBackground(new java.awt.Color(37, 50, 55));
        jButtonAnnulla.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jButtonAnnulla.setForeground(new java.awt.Color(248, 248, 255));
        jButtonAnnulla.setText("Annulla");
        jButtonAnnulla.setBorder(null);
        jButtonAnnulla.setFocusPainted(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonConferma, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAnnulla, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jSpinnerR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jSpinnerG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonConferma, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jButtonAnnulla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Variables declaration
    // <editor-fold defaultstate="collapsed" desc="Varaibles declaration"> 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnulla;
    private javax.swing.JButton jButtonConferma;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerB;
    private javax.swing.JSpinner jSpinnerG;
    private javax.swing.JSpinner jSpinnerR;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
    
    public JButton getjButtonAnnulla() {
        return this.jButtonAnnulla;
    }

    public JButton getjButtonConferma() {
        return this.jButtonConferma;
    }

    public JComboBox<String> getjComboBoxTipo() {
        return this.jComboBoxTipo;
    }

    public JSpinner getjSpinnerB() {
        return this.jSpinnerB;
    }

    public JSpinner getjSpinnerG() {
        return this.jSpinnerG;
    }

    public JSpinner getjSpinnerR() {
        return this.jSpinnerR;
    }

    public void setPl(PanelLuci pl) {
        this.pl = pl;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==this.jComboBoxTipo){
            switch((String)this.jComboBoxTipo.getSelectedItem()){
                case "Generic DMX":
                    this.jSpinnerR.setValue(this.ac.getLastChannel());
                    this.jSpinnerG.setValue(this.ac.getLastChannel());
                    this.jSpinnerB.setValue(this.ac.getLastChannel());
                    this.jSpinnerG.setEnabled(true);
                    this.jSpinnerB.setEnabled(true);
                    break;
                case "RGB Lamp":
                    this.jSpinnerR.setValue(this.ac.getLastChannel());
                    this.jSpinnerG.setValue((int)this.jSpinnerR.getValue()+1);
                    this.jSpinnerB.setValue((int)this.jSpinnerG.getValue()+1);
                    this.jSpinnerG.setEnabled(false);
                    this.jSpinnerB.setEnabled(false);
                    break;
                default:
                    break;
            }
        }
        else if(e.getSource()==this.jButtonConferma){
            if(this.isEdit){
                this.ac.editLuce(this.index, (Integer)this.jSpinnerR.getValue(), 3, (String)this.jComboBoxTipo.getSelectedItem(), (Integer)this.jSpinnerR.getValue(), (Integer)this.jSpinnerG.getValue(), (Integer)this.jSpinnerB.getValue());
            }
            else{
                this.ac.addLuce(new Luce((Integer)this.jSpinnerR.getValue(), 3, (String)this.jComboBoxTipo.getSelectedItem(), (Integer)this.jSpinnerR.getValue(), (Integer)this.jSpinnerG.getValue(), (Integer)this.jSpinnerB.getValue()));
            }
            this.setVisible(false);
            this.pl.refreshLuci();
        }
        else if(e.getSource()==this.jButtonAnnulla){
            this.setVisible(false);
            this.pl.refreshLuci();
        }
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        if(e.getSource()==this.jSpinnerR && this.jComboBoxTipo.getSelectedItem().equals("RGB Lamp")){
            this.jSpinnerG.setValue((Integer)this.jSpinnerR.getValue());
            this.jSpinnerB.setValue((Integer)this.jSpinnerG.getValue());
        }
    }
    
}
